language: node_js
node_js:
  - 'node'
cache:
  - directories:
    - "node_modules"
install:
  - npm install
  - npm update
script:
  - NODE_ENV=production npm run test
env:
  global:
    - COVERAGE_TYPE: lcov
